# Generated by Django 3.2.4 on 2021-06-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90, verbose_name='Country')),
                ('Latitude', models.FloatField(verbose_name='Latitude')),
                ('Longitude', models.FloatField(verbose_name='Longitude')),
                ('Code', models.CharField(max_length=4, verbose_name='Code')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90, verbose_name='State')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressBook.country')),
            ],
            options={
                'db_table': 'State',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Address')),
                ('HouseNo', models.CharField(max_length=90, verbose_name='House No')),
                ('RoadNo', models.IntegerField(verbose_name='Road No')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressBook.country', verbose_name='Country')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressBook.state', verbose_name='State')),
            ],
            options={
                'db_table': 'Address',
                'managed': True,
            },
        ),
    ]
